pipeline:
  build:
    image: python
    commands:
      - pip install tailer

  clair:
    image: poke/drone-clair:latest
    url: http://linuxsysadmin.hu:6060
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    scan_image: python