pipeline:
  build:
    image: python
    commands:
      - pip install tailer

  clair:
    image: jmccann/drone-clair:1
    url: http://linuxsysadmin.hu:8080
    username: poke
    password: poke
    scan_image: python:2.7