pipeline:
  build:
    image: python
    commands:
      - pip install tailer

  test_poke:
    image: poke/drone-clair:latest
    url: http://linuxsysadmin.hu:6060
    username: poke
    scan_image: python
    secrets: [ docker_password ]