pipeline:
  build:
    image: python
    commands:
      - pip install tailer

  clair:
    image: jmccann/drone-clair:1
    url: http://linuxsysadmin.hu:8080
    secrets: [ docker_username, docker_password ]
    scan_image: python:2.7